name: Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with: {python-version: 2.7}
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with: {python-version: 3.5}
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with: {python-version: 3.6}
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with: {python-version: 3.7}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with: {python-version: 3.8}
    - name: Cache pip (Linux)
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade flit
        flit install --symlink
    - name: Test with pytest
      run: |
        tox -- --cov=src/sqreen_security_signal_sdk --cov-report=xml tests
      env:
        TOX_PARALLEL_NO_SPINNER: 1
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
